### ISSUE TITLE
"Why must I attend" link on the meeting schedule header doesn't go anywhere.

### ISSUE THREAD

**Issue by luke80** [BYU-IS-Media/HTML-BYU_Online-TemplateFork#1]
Kyle,

I'm not 100% sure if this is meant to be a "popup" thing, or a separate page.

If it is a popup thing I can add in that functionality (or teach you if you have time/want)
If it is a new page - I believe you could make one of those! If you want a quick pointer I'm happy to help, or if you are out of time I can do it instead. Let me know, please!

--Luke

**Comment by mkylemartin** [comment]
I would love to see how to make it a pop-up thing or a separate page but I won't be in today because I have a test to take. Let's see what Carolyn wants it to do and go from there. On Monday you could show me what you ended up doing. 

Thanks for your help, I really enjoy learning all this stuff!

Kyle
